# Generated by Django 3.0.3 on 2020-02-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
